version: '3.3'

services:
  db:
    build:
      context: .
      dockerfile: bsa-db.Dockerfile
    environment:
      POSTGRES_DB: bsadb
      POSTGRES_USER: bsa
      POSTGRES_PASSWORD: bsa
    networks:
      - app-network
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bsa -d bsadb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: bsa-server.Dockerfile
    environment:
      DATABASE_URL: db://bsa:bsa@db/bsadb
    depends_on:
      # - job
      - db
    networks:
      - app-network
    ports:
      - "3003:3003"
    entrypoint: ["node", "index.js"]

  # job:
  #   build:
  #     context: .
  #     dockerfile: bsa-jobs.Dockerfile
  #   depends_on:
  #     - db
  #   networks:
  #     - app-network
  #   entrypoint: ["sh", "scripts/refreshdb.sh"]
  #   restart: "no"
  
volumes:
  db-data:

networks:
  app-network:
    driver: bridge
